### ISSUE TITLE
Investigate the possibility of loading rules parts into main

### ISSUE THREAD

**Issue by atorkmabrains** [google/globalfoundries-pdk-libs-gf180mcu_fd_pv#16]
@proppy I tried that using `require` in ruby doesn't work well in klayout for some reason. The best way to do this is to include all the rule deck here as you mentioned and to avoid the need to concatenate files in python. But I tried several solutions non worked with klayout. The solutions work outside of klayout on a regular ruby script.

References:
- https://stackoverflow.com/questions/3672586/what-is-the-difference-between-require-relative-and-require-in-ruby
 - https://medium.com/@connorstack/understanding-ruby-load-require-gems-bundler-and-rails-autoloading-from-the-bottom-up-3b422902ca0

**Comment by proppy** [comment]
why not use `%include` as described in https://www.klayout.de/doc/manual/drc_runsets.html#:~:text=objects%20and%20methods.-,Including%20other%20files,-The%20DRC%20script ?

**Comment by atorkmabrains** [comment]
@proppy Let's give it a try in the next update.

**Comment by proppy** [comment]
note that this is also preventing to run the drc script in a standalone manner:
```
$ klayout -b -r dualgate.drc  ~/src/github.com/efabless/caravel_user_project/gds/user_proj_example.gds 
ERROR: In dualgate.drc: 'output': no implicit conversion of String into Integer for argument #1 ('layer') in LayerInfo::initialize
ERROR: 'output': no implicit conversion of String into Integer for argument #1 ('layer') in LayerInfo::initialize in Executable::execute
  dualgate.drc:37:in `execute'
  :/built-in-macros/drc_interpreters.lym:27:in `instance_eval'
  :/built-in-macros/drc_interpreters.lym:27:in `execute'
```

It would be nice to have all script be standalone and self-dependant, and keep `main.drc` for high level orchestration.

**Comment by atorkmabrains** [comment]
@proppy That's why `run_drc.py` exists. It could what you described above.

**Comment by atorkmabrains** [comment]
@proppy Could you please add @FaragElsayed2 to the repo, I can't assign tickets to him?

**Comment by proppy** [comment]
@atorkmabrains can't you tag them in the issue comments? (I'm not sure if we can add people outside of the google's org, maybe @mithro has more insight)

**Comment by atorkmabrains** [comment]
@mithro Could you please add @FaragElsayed2  to the project? I can't assign him to any of the tickets.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Please work on this.

**Comment by atorkmabrains** [comment]
Thanks @proppy

**Comment by atorkmabrains** [comment]
@proppy We have completed this investigation and we think that we can use `# %include` in the code and it works well.
