### ISSUE TITLE
Create a project on this repo and set priorities for issues

### ISSUE THREAD

**Issue by atorkmabrains** [google/globalfoundries-pdk-libs-gf180mcu_fd_pv#41]
@proppy Could you please create a a project on this repo to be able to track progress on this repo? Also, moving forward, Could we please set priorities of issues that you want us to address from your perspective to avoid adding PRs that is on hold and reset and reverting changes? It helps us save time.

cc @mithro @FaragElsayed2

**Comment by atorkmabrains** [comment]
@proppy Please make sure to update this issue. It's very important for me to be able to set priorities.

**Comment by proppy** [comment]
Sure, created https://github.com/orgs/google/projects/57 and added you as an admin.

**Comment by atorkmabrains** [comment]
Thanks @proppy But now, I need your insight on the order of issues that we should address first? You could list them today or I could list them on Sunday. I just want to set priorities and order.

**Comment by atorkmabrains** [comment]
@proppy I have added all issues, Could you please add priorities? I'll re-open the issue until we complete the project issues discussion.

**Comment by proppy** [comment]
@mithro in case he also want to partipate in the prioritization effort.

**Comment by atorkmabrains** [comment]
He is assigned to this issue I believe. I have added all issues and I made this as the top issue and left the rest for you to change order and status:

https://github.com/orgs/google/projects/57/views/1

**Comment by atorkmabrains** [comment]
@proppy and @mithro  I have changed the view to more like a project management. Please move the issues to "To Do" and I'll know whom to assign for those tasks.

**Comment by proppy** [comment]
@atorkmabrains I moved the item that I think are I think are important (around making the DRC deck complete, lint clean and allowing interactive usage) in TODO.

But I'd leave it to @mithro and you to figure out what you think should be addressed first.
