### ISSUE TITLE
Converting the whole block of metal stack layers definitions in a big case statement

### ISSUE THREAD

**Issue by FaragElsayed2** [google/globalfoundries-pdk-libs-gf180mcu_fd_pv#42]
## Converting the whole block of metal stack layers definitions in a big case statement

**Comment by FaragElsayed2** [comment]
@atorkmabrains I think this issue has been solved in this [PR](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv/pull/46)

Check this [line](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv/pull/46/files#diff-2fc1909b24080db58ac26eab41b0eb351681f3af1fda053498359ecd29579be2R553)

**Comment by atorkmabrains** [comment]
@proppy Could you close this ticket as I believe this has been addressed?
