### ISSUE TITLE
DRC hits on implant layers

### ISSUE THREAD

**Issue by lrburle** [google/globalfoundries-pdk-libs-gf180mcu_fd_pv#45]
## Environment

- Klayout Version: 0.28.5
- OS/Platform: Ubuntu 20.04

I have ran the above script as shown by the README.md in the repo using this command: "python3 run_drc.py --path=user_project_wrapper.gds --variant=C --verbose --mp=4 --topcell=user_project_wrapper --thr=8 --connectivity --density --antenna --no_offgrid" . I am still seeing the DRC as mentioned before. The majority of the DRC is stemming from NP.2, NP.5b, PP.5b, and PP.8a. All of which seem to be hitting on the implant layers that are automatically generated and placed into the GDS upon extraction from magic (See screenshot in the attached zip, the layer that is shown to be too close is a layer that we did not place manually in the standard cell layouts). Also inside the zip file is the gds and lyrdb files as needed.

[implant_layers_issue_files.zip](https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pv/files/10814318/implant_layers_issue_files.zip)

**Comment by atorkmabrains** [comment]
Thanks @lrburle we will take a look.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 could you please check this?

**Comment by FaragElsayed2** [comment]
Hi @lrburle and @atorkmabrains 

- For NP.2 rule, there are real violations in the provided testcase 

![image](https://user-images.githubusercontent.com/91015308/221409923-d0be242b-92ba-4549-8d5b-3d92bc584e29.png)

![image](https://user-images.githubusercontent.com/91015308/221409906-9a8120e2-bd5f-43c3-977b-f47d93b02429.png)

- NP.5b & PP.5b rules have been modified to behave as expected.

- For PP.8a rule, there are real violations in the provided testcase 

![image](https://user-images.githubusercontent.com/91015308/221411654-c802f99d-101c-47e3-9f82-9ccf0489d86f.png)

![image](https://user-images.githubusercontent.com/91015308/221411716-9277256e-934f-4c93-bcad-08fa3e5fa6bd.png)

**Comment by atorkmabrains** [comment]
@lrburle Could you please check?

**Comment by lrburle** [comment]
@atorkmabrains The changes found in the np_pp_fixup_efab branch [here ](https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv/tree/np_pp_fixup_efab) fixed the PP.5b and NP.5b issues for me.
